---
- include_vars: config.yml

- stat: path=/etc/ssl/certs/dhparam.pem
  register: hdparam_file

- name: config - configure openssl
  command: "openssl dhparam -out dhparam.pem {{nginx_openssl_hdparam_bits}}"
  args:
    chdir: /etc/ssl/certs
  when: not hdparam_file.stat.exists

- name: config - ensure sites directories
  file:
    state=directory
    path={{ item }}
    mode=0755
  with_items:
    - "{{ nginx_sites_enabled_dir }}"
    - "{{ nginx_sites_available_dir }}"

- name: config - global configs copy
  copy:
    src=global/
    dest={{ nginx_global_dir }}
    force=yes

- name: config - root configs copy
  copy:
    src=root/
    dest={{ nginx_config_dir }}
    mode=0644
    force=yes
  notify: restart nginx

- name: config - pagespeed
  template:
    src=global/{{ item }}.j2
    dest={{ nginx_global_dir }}/{{ item }}
    mode=0644
    force=yes
  with_items:
    - pagespeed.conf
    - pagespeed-stats.conf
    - pagespeed-location.conf
  when: nginx_pagespeed_build
  notify: restart nginx

- name: config - global templates
  template:
    src=global/{{ item }}.j2
    dest={{ nginx_global_dir }}/{{ item }}
    mode=0644
    force=yes
  with_items:
    - acl-stats.conf
    - real-ip.conf
    - proxy-cache-path.conf
  notify: restart nginx

- name: config - configure root nginx.conf
  template:
    src=nginx.conf.j2
    dest={{ nginx_config_dir }}/nginx.conf
    validate='{{ nginx_bin }} -t -c %s'
    mode=0644
    force=yes
  notify: restart nginx

- name: config - configure health.site
  template:
    src=health.site.j2
    dest={{ nginx_sites_enabled_dir}}/health.site
    mode=0644
    force=yes
  notify: restart nginx

  #- name: config - test config
  #  command: "{{ nginx_bin }} -t -c {{ nginx_config_dir }}/nginx.conf"
  #  register: nginx_test
  #  changed_when: False
  #
  #- debug: var=nginx_test
  #  when: nginx_test.rc != 0
  #
  #- fail: msg="incorrect config"
  #  when: nginx_test.rc != 0

