---
- include_vars: config.yml

- stat: path=/etc/ssl/certs/dhparam.pem
  register: hdparam_file

- name: config - configure openssl
  command: "openssl dhparam -out dhparam.pem {{nginx_openssl_hdparam_bits}}"
  args:
    chdir: /etc/ssl/certs
  when: not hdparam_file.stat.exists

- name: config - configure mime.types
  copy:
    src=mime.types
    dest={{ nginx_config_dir }}
    mode=0644
  notify: reload nginx

- name: config - configure root nginx.conf
  template:
    src=nginx.conf.j2
    dest={{ nginx_config_dir }}/nginx.conf
    validate='{{ nginx_bin }} -t -c %s'
    mode=0644
  notify: reload nginx

- name: config - configure health.site
  template:
    src=health.site.j2
    dest={{ nginx_config_dir }}/sites-enabled/health.site
    mode=0644
    backup=yes
  notify: reload nginx

- name: config - test config
  command: "{{ nginx_bin }} -t -c {{ nginx_config_dir }}/nginx.conf"
  register: nginx_test
  changed_when: False

- debug: var=nginx_test
  when: nginx_test.rc != 0

- fail: msg="incorrect config"
  when: nginx_test.rc != 0

