- name: depend - install Debian packages
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_flattened: [nginx_debian_packages, debian_build_essential]
  when: ansible_os_family == "Debian"

- name: depend - install CentOS packages
  yum:
    name={{ item }}
    state=present
    update_cache=yes
  with_flattened: [nginx_centos_packages, centos_build_essential]
  when: ansible_os_family == "RedHat"

