---
# tasks file for nginx

- include: depend.yml
- include: setup.yml
- include: ngx_txid.yml

- include: pagespeed.yml
  when: nginx_pagespeed_build

- include: naxsi.yml
  when: nginx_naxsi_build

- include: install_source.yml
- include: config.yml

- include: runit_service.yml
  vars:
    service_name: "{{ nginx_service_name }}"
    service_user: "{{ nginx_user }}" 
    service_command: "{{ nginx_bin }} -c {{ nginx_config_dir }}/nginx.conf"

