---
# tasks file for nginx

- include: depend.yml
- include: setup.yml
- include: modules.yml

- include: pagespeed.yml
  when: nginx_pagespeed_build

- include: naxsi.yml
  when: nginx_naxsi_build

- include: install_source.yml

- name: general config
  include: config.yml

- name: service
  include: service.yml

