---

- name: modules - unarchive modules
  unarchive:
    src={{ item }}
    dest={{ nginx_build_folder }}
    copy=yes
  with_items:
    - "{{ nginx_module_ngx_txid_file }}"
    - "{{ nginx_module_ngx_cache_purge_file }}"
    - "{{ nginx_module_ngx_http_headers_more_file }}"

