---

- name: service - setup and run
  runit:
    name: "{{ nginx_service_name }}"
    enabled: yes
    state: start
    timeout: 10
    user: root
    command: "{{ nginx_bin }} -c {{ nginx_config_dir }}/nginx.conf"
  register: nginx_service_status

