
- name: create nginx group
  group:
    name={{ nginx_group }}
    state=present
    system=yes

- name: create nginx user
  user:
    name={{ nginx_user }}
    group={{ nginx_group }}
    createhome=no
    system=yes

- name: setup build folder
  file:
    state=directory
    path={{ nginx_build_folder }}

- name: setup - create directories
  file:
    state=directory
    path={{ item }}
    owner={{ nginx_user }}
    group={{ nginx_group }}
    mode=0755
  with_items:
    - "{{ nginx_config_dir }}"
    - "{{ nginx_sites_enabled_dir }}"
    - "{{ nginx_sites_available_dir }}"
    - "{{ nginx_global_dir }}"
    - "{{ nginx_shared_dir }}"
    - "{{ nginx_log_dir }}"
    - /var/lib/nginx/tmp/client_body
    - /var/lib/nginx/tmp/proxy
    - /var/lib/nginx/tmp/fastcgi
    - /etc/ssl/certs

- name: setup - directories for pagespeed
  file:
    state=directory
    path={{ item }}
    owner={{ nginx_user }}
    group={{ nginx_group }}
    mode=0755
  with_items:
    - "{{ nginx_pagespeed_cache_dir }}"
    - "{{ nginx_pagespeed_log_dir }}"
  when: nginx_pagespeed_build

