---

- name: restart nginx
  runit: name={{ nginx_service_name }} state=up timeout=9 action=restart
  when: not nginx_service_status.restarted

- name: reload nginx
  runit: name={{ nginx_service_name }} state=up timeout=9 action=reload



