---

- name: restart nginx
  runit:
    name={{ nginx_service_name }}
    action=restart
    state=up
    enabled=true
    timeout=9
  when: not nginx_service_status.restarted

- name: reload nginx
  runit: 
    name={{ nginx_service_name }} 
    action=reload
    state=up
    enabled=true
    timeout=9



